import pandas as pd
df = pd.read_csv("ml/artifacts/fold_trades_model_4_fold_2.csv")
print("dtypes:")
print(df.dtypes)
print()
print("pnl sample:", df["pnl"].head(5).tolist())
df["pnl"] = pd.to_numeric(df["pnl"], errors="coerce")
print()
print(f"after numeric coerce -- total pnl: {df.pnl.sum():.2f}")
print(f"avg_win:  {df[df.pnl > 0].pnl.mean():.2f}")
print(f"avg_loss: {df[df.pnl < 0].pnl.mean():.2f}")
print(f"win_rate: {(df.pnl > 0).mean():.2%}")
print(f"expectancy per trade: {df.pnl.mean():.2f}")
print(f"largest win:  {df.pnl.max():.2f}")
print(f"largest loss: {df.pnl.min():.2f}")
print(f"trades: {len(df)}")
